### ISSUE TITLE
Rasa X 0.26.1 does not pull messages from RabbitMQ queue

### ISSUE THREAD

**Issue by sinhlt58** [RasaHQ/rasa#5452]
**Rasa version**: 1.8.0

**Rasa SDK version** (if used & relevant): 1.8.1

**Rasa X version** (if used & relevant): 0.26.1

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: Hi guys. I have a running rasa open source running on a machine and rasa-x running on a different machine. I have successfully configured connecting between the two machines. So, I can import data from my gitlab repository and train my models with rasa-x. But the problem is that when I chat with my agent using the REST channel through rasa open source (/webhooks/rest/webhook) the conversations doesn't show up on rasa-x conversation tab. The messages do show up on RabbitMQ but it seems like rasa-x does not pull messages from the RabbitMQ server.

**RabbitMQ image**
![rabbit](https://user-images.githubusercontent.com/10632704/77133927-8019c580-6a97-11ea-91f4-8fd7526625b3.png)

**rasa-x UI conversations is empty**
![conversations](https://user-images.githubusercontent.com/10632704/77133944-91fb6880-6a97-11ea-97ba-afbdd427bc2f.png)

**rasa-x UI models**
![models](https://user-images.githubusercontent.com/10632704/77133957-9b84d080-6a97-11ea-83bb-32cdaec0601b.png)

**rasa-x log**
```
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): pypi.rasa.com:80
DEBUG:urllib3.connectionpool:http://pypi.rasa.com:80 "GET /api/package/rasa-x HTTP/1.1" 302 208
DEBUG:urllib3.connectionpool:http://pypi.rasa.com:80 "GET /api/package/rasa-x/ HTTP/1.1" 200 472592
Starting Rasa X server... 🚀
[2020-03-20 03:29:54 +0000] [7] [DEBUG] 

                 Sanic
         Build Fast. Run Fast.


[2020-03-20 03:29:54 +0000] [7] [INFO] Goin' Fast @ http://0.0.0.0:5002
DEBUG:rasax.community.telemetry:Sending periodic telemetry event.
[2020-03-20 03:29:54 +0000] [37] [INFO] Starting worker [37]
[2020-03-20 03:29:54 +0000] [38] [INFO] Starting worker [38]
[2020-03-20 03:29:54 +0000] [35] [INFO] Starting worker [35]
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.2.86:9999
DEBUG:urllib3.connectionpool:http://192.168.2.86:9999 "GET /version HTTP/1.1" 200 58
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.2.86:9998
DEBUG:urllib3.connectionpool:http://192.168.2.86:9998 "GET /version HTTP/1.1" 200 58
[2020-03-20 03:29:55 +0000] [36] [INFO] Starting worker [36]
....
[2020-03-20 03:38:36 +0000] [38] [DEBUG] CORS: Request to '/conversations' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
DEBUG:rasax.community.api.blueprints.interface:Answered 404 with index.html. Request url '/': 'http://172.16.70.198:5002/conversations'
[2020-03-20 03:38:36 +0000] [38] [DEBUG] CORS: CORS was handled in the exception handler, skipping
[2020-03-20 03:38:36 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: GET http://172.16.70.198:5002/conversations  200 3173
[2020-03-20 03:38:36 +0000] [38] [DEBUG] CORS: Request to '/static/css/2.20a0f44c.chunk.css' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:36 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: GET http://172.16.70.198:5002/static/css/2.20a0f44c.chunk.css  304 0
[2020-03-20 03:38:36 +0000] [38] [DEBUG] CORS: Request to '/static/media/conversations_placeholder.6ff85dae.svg' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:36 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: GET http://172.16.70.198:5002/static/media/conversations_placeholder.6ff85dae.svg  304 0
[2020-03-20 03:38:36 +0000] [35] [DEBUG] CORS: Request to '/fonts/lato-v14-latin/lato-v14-latin-700.woff2' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:36 +0000] - (sanic.access)[INFO][172.16.70.198:40808]: GET http://172.16.70.198:5002/fonts/lato-v14-latin/lato-v14-latin-700.woff2  304 0
[2020-03-20 03:38:36 +0000] [38] [DEBUG] CORS: Request to '/fonts/lato-v14-latin/lato-v14-latin-regular.woff2' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:36 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: GET http://172.16.70.198:5002/fonts/lato-v14-latin/lato-v14-latin-regular.woff2  304 0
[2020-03-20 03:38:37 +0000] [35] [DEBUG] CORS: Request to '/api/conversations/tags' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] [38] [DEBUG] CORS: Request to '/api/projects/default/git_repositories' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40808]: GET http://172.16.70.198:5002/api/conversations/tags  200 2
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: GET http://172.16.70.198:5002/api/projects/default/git_repositories  200 152
[2020-03-20 03:38:37 +0000] [36] [DEBUG] CORS: Request to '/api/conversationIntents' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40812]: GET http://172.16.70.198:5002/api/conversationIntents  200 2
[2020-03-20 03:38:37 +0000] [37] [DEBUG] CORS: Request to '/api/projects/default/intents' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40810]: GET http://172.16.70.198:5002/api/projects/default/intents?fields[example_hashes]=false&fields[suggestions]=false  200 1849
[2020-03-20 03:38:37 +0000] [35] [DEBUG] CORS: Request to '/api/conversations/slotNames' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40814]: GET http://172.16.70.198:5002/api/conversations/slotNames  200 2
[2020-03-20 03:38:37 +0000] [38] [DEBUG] CORS: Request to '/api/conversationPolicies' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: GET http://172.16.70.198:5002/api/conversationPolicies  200 2
[2020-03-20 03:38:37 +0000] [36] [DEBUG] CORS: Request to '/api/conversations/inputChannels' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40812]: GET http://172.16.70.198:5002/api/conversations/inputChannels  200 2
[2020-03-20 03:38:37 +0000] [35] [DEBUG] CORS: Request to '/api/conversationEntities' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40816]: GET http://172.16.70.198:5002/api/conversationEntities  200 2
[2020-03-20 03:38:37 +0000] [38] [DEBUG] CORS: Request to '/api/telemetry' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40806]: POST http://172.16.70.198:5002/api/telemetry  204 0
[2020-03-20 03:38:37 +0000] [37] [DEBUG] CORS: Request to '/api/projects/default/entities' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40810]: GET http://172.16.70.198:5002/api/projects/default/entities  200 61
[2020-03-20 03:38:37 +0000] [35] [DEBUG] CORS: Request to '/api/conversationActions' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40808]: GET http://172.16.70.198:5002/api/conversationActions  200 2
[2020-03-20 03:38:37 +0000] [36] [DEBUG] CORS: Request to '/api/conversations' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40812]: GET http://172.16.70.198:5002/api/conversations?limit=20&offset=0&intent=&entity=&action=&policies=&slots=&input_channels=&tags_any=&with_tags=true&interactive=true&exclude_self=true  200 2
[2020-03-20 03:38:37 +0000] [35] [DEBUG] CORS: Request to '/api/features' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40816]: GET http://172.16.70.198:5002/api/features  200 2
DEBUG:git.cmd:Popen(['git', 'fetch'], cwd=/app/git/1, universal_newlines=False, shell=None, istream=None)
[2020-03-20 03:38:37 +0000] [36] [DEBUG] CORS: Request to '/static/media/onboarding_create.c1ddd659.svg' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40812]: GET http://172.16.70.198:5002/static/media/onboarding_create.c1ddd659.svg  304 0
[2020-03-20 03:38:37 +0000] [36] [DEBUG] CORS: Request to '/static/media/onboarding_maintain.14c39143.svg' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40812]: GET http://172.16.70.198:5002/static/media/onboarding_maintain.14c39143.svg  304 0
[2020-03-20 03:38:37 +0000] [36] [DEBUG] CORS: Request to '/icons/favicon.ico' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40812]: GET http://172.16.70.198:5002/icons/favicon.ico  200 6518
DEBUG:git.cmd:Popen(['git', 'rev-list', 'master..origin/master', '--'], cwd=/app/git/1, universal_newlines=False, shell=None, istream=None)
DEBUG:rasax.community.services.integrated_version_control.git_service:Branch 'master' is 0 commits behind 'master'.
DEBUG:git.cmd:Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/app/git/1, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/app/git/1, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/app/git/1, universal_newlines=False, shell=None, istream=None)
[2020-03-20 03:38:37 +0000] [35] [DEBUG] CORS: Request to '/api/projects/default/git_repositories/1/status' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
[2020-03-20 03:38:37 +0000] - (sanic.access)[INFO][172.16.70.198:40816]: GET http://172.16.70.198:5002/api/projects/default/git_repositories/1/status  200 240
```
 
**rasa-production log**:
```
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-03-20 03:32:07 INFO     root  - Starting Rasa server on http://localhost:5005
2020-03-20 03:32:07 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-03-20 03:32:07 INFO     root  - Enabling coroutine debugging. Loop id 76696056.
2020-03-20 03:32:07 DEBUG    rasa.model  - Extracted model to '/tmp/tmpc90lqx_3'.
2020-03-20 03:32:07 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-03-20 03:32:07.963475: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-03-20 03:32:08 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-03-20 03:32:08 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-03-20 03:32:12 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-03-20 03:32:12 DEBUG    rasa.core.brokers.broker  - Instantiated event broker to 'PikaEventBroker'.
2020-03-20 03:32:12 DEBUG    rasa.core.tracker_store  - Connected to RedisTrackerStore.
2020-03-20 03:32:12 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-03-20 03:32:12 DEBUG    rasa.core.brokers.pika  - RabbitMQ connection to '172.16.70.198' was established.
2020-03-20 03:32:12 DEBUG    rasa.core.brokers.pika  - RabbitMQ channel was opened.
2020-03-20 03:32:13 DEBUG    rasa.model  - Extracted model to '/tmp/tmpzr961x6k'.
2020-03-20 03:32:13 DEBUG    pykwalify.compat  - Using yaml library: /usr/local/lib/python3.6/dist-packages/ruamel/yaml/__init__.py
2020-03-20 03:32:13 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-03-20 03:32:13 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-03-20 03:32:13 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-03-20 03:32:14 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-03-20 03:32:14 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-03-20 03:32:59 DEBUG    rasa.core.processor  - Starting a new session for conversation ID 'test_rasa_x'.
2020-03-20 03:32:59 DEBUG    rasa.core.processor  - Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x7fbc9cd24518>, <rasa.core.events.ActionExecuted object at 0x7fbc9cd244e0>]'.
2020-03-20 03:32:59 DEBUG    rasa.core.processor  - Current slot values: 
	order_id: None
	requested_slot: None
	role: None
	user_id: None
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9569578170776367}' and entities '[]'
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 4 events.
2020-03-20 03:33:00 DEBUG    rasa.core.policies.form_policy  - There is no active form
2020-03-20 03:33:00 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
2020-03-20 03:33:00 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '9'
2020-03-20 03:33:00 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.5).
2020-03-20 03:33:00 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_MemoizationPolicy
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Predicted next action 'action_greet' with confidence 1.00.
2020-03-20 03:33:00 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_greet'.
2020-03-20 03:33:00 DEBUG    rasa_sdk.executor  - Received request to run 'action_greet'
2020-03-20 03:33:00 DEBUG    rasa_sdk.executor  - Finished running 'action_greet'
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Action 'action_greet' ended with events '[BotUttered('Cảm ơn bạn đã liên hệ. Vui lòng cho GHTK biết, bạn là shop hay khách:', {"elements": null, "quick_replies": null, "buttons": [{"payload": "la shop ghtk", "title": "Shop"}, {"payload": "la khach", "title": "Kh\u00e1ch"}], "attachment": null, "image": null, "custom": null}, {}, 1584675180.1313426)]'.
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Current slot values: 
	order_id: None
	requested_slot: None
	role: None
	user_id: None
2020-03-20 03:33:00 DEBUG    rasa.core.policies.form_policy  - There is no active form
2020-03-20 03:33:00 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_greet': 1.0, 'intent_greet': 1.0}]
2020-03-20 03:33:00 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '0'
2020-03-20 03:33:00 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'greet'.
2020-03-20 03:33:00 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.5).
2020-03-20 03:33:00 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_MemoizationPolicy
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
2020-03-20 03:33:00 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'.
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "action", "timestamp": 1584675179.8754637, "name": "action_session_start", "policy": null, "confidence": null}
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "session_started", "timestamp": 1584675179.8754687}
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "action", "timestamp": 1584675179.8754826, "name": "action_listen", "policy": null, "confidence": null}
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "user", "timestamp": 1584675180.0946395, "text": "hi", "parse_data": {"intent": {"name": "greet", "confidence": 0.9569578170776367}, "entities": [], "intent_ranking": [{"name": "greet", "confidence": 0.9569578170776367}, {"name": "order_push_deliver", "confidence": 0.008399023674428463}, {"name": "ask_push", "confidence": 0.007219584658741951}, {"name": "order_modify_phone", "confidence": 0.00535670155659318}, {"name": "order_complain_break", "confidence": 0.005030442029237747}, {"name": "continue", "confidence": 0.00454800995066762}, {"name": "select_guest", "confidence": 0.003924046643078327}, {"name": "account_modify_bank", "confidence": 0.003417240921407938}, {"name": "ghtk_app_help", "confidence": 0.0030343378894031048}, {"name": "ask_advise", "confidence": 0.002112732967361808}], "text": "hi"}, "input_channel": "rest", "message_id": "1349571655624e07969cac2ab168ee76", "metadata": {}}
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "action", "timestamp": 1584675180.1315086, "name": "action_greet", "policy": "policy_1_MemoizationPolicy", "confidence": 1.0}
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "bot", "timestamp": 1584675180.131515, "text": "C\u1ea3m \u01a1n b\u1ea1n \u0111\u00e3 li\u00ean h\u1ec7. Vui l\u00f2ng cho GHTK bi\u1ebft, b\u1ea1n l\u00e0 shop hay kh\u00e1ch:", "data": {"elements": null, "quick_replies": null, "buttons": [{"payload": "la shop ghtk", "title": "Shop"}, {"payload": "la khach", "title": "Kh\u00e1ch"}], "attachment": null, "image": null, "custom": null}, "metadata": {}}
2020-03-20 03:33:00 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "action", "timestamp": 1584675180.1523867, "name": "action_listen", "policy": "policy_1_MemoizationPolicy", "confidence": 1.0}
2020-03-20 03:33:00 DEBUG    rasa.core.lock_store  - Deleted lock for conversation 'test_rasa_x'.
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Received user message 'shop' with intent '{'name': 'select_shop', 'confidence': 0.9640088081359863}' and entities '[]'
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 8 events.
2020-03-20 03:33:17 DEBUG    rasa.core.policies.form_policy  - There is no active form
2020-03-20 03:33:17 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_greet': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_select_shop': 1.0}]
2020-03-20 03:33:17 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-03-20 03:33:17 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.5).
2020-03-20 03:33:17 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_3_TEDPolicy
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Predicted next action 'action_select_shop' with confidence 0.90.
2020-03-20 03:33:17 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_select_shop'.
2020-03-20 03:33:17 DEBUG    rasa_sdk.executor  - Received request to run 'action_select_shop'
2020-03-20 03:33:17 DEBUG    rasa_sdk.executor  - Finished running 'action_select_shop'
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Action 'action_select_shop' ended with events '[BotUttered('Shop đã có tài khoản của GHTK chưa ạ?', {"elements": null, "quick_replies": null, "buttons": [{"payload": "khach thuong xuyen", "title": "\u0110\u00e3 c\u00f3 t\u00e0i kho\u1ea3n GHTK"}, {"payload": "khach hang moi", "title": "Ch\u01b0a c\u00f3 t\u00e0i kho\u1ea3n GHTK"}], "attachment": null, "image": null, "custom": null}, {}, 1584675197.8802612), <rasa.core.events.SlotSet object at 0x7fbcd8e9ac50>]'.
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Current slot values: 
	order_id: None
	requested_slot: None
	role: SHOP
	user_id: None
2020-03-20 03:33:17 DEBUG    rasa.core.policies.form_policy  - There is no active form
2020-03-20 03:33:17 DEBUG    rasa.core.policies.memoization  - Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_greet': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_select_shop': 1.0}, {'intent_select_shop': 1.0, 'prev_action_select_shop': 1.0}]
2020-03-20 03:33:17 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-03-20 03:33:17 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'select_shop'.
2020-03-20 03:33:17 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.5).
2020-03-20 03:33:17 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_3_TEDPolicy
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 0.98.
2020-03-20 03:33:17 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'.
2020-03-20 03:33:17 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "user", "timestamp": 1584675197.862185, "text": "shop", "parse_data": {"intent": {"name": "select_shop", "confidence": 0.9640088081359863}, "entities": [], "intent_ranking": [{"name": "select_shop", "confidence": 0.9640088081359863}, {"name": "ask_service", "confidence": 0.007028357591480017}, {"name": "ask_cod", "confidence": 0.004847100004553795}, {"name": "ask_complain", "confidence": 0.004720245487987995}, {"name": "order_cod_lack", "confidence": 0.0039013270288705826}, {"name": "ask_schedule", "confidence": 0.0037461023312062025}, {"name": "order_complain_break", "confidence": 0.003101280191913247}, {"name": "order_schedule_deliver", "confidence": 0.003010442480444908}, {"name": "select_shopee", "confidence": 0.002822794485837221}, {"name": "rules_transfer_fee", "confidence": 0.00281353946775198}], "text": "shop"}, "input_channel": "rest", "message_id": "f4b687d9cfa645aa84dba97020483983", "metadata": {}}
2020-03-20 03:33:17 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "action", "timestamp": 1584675197.8804069, "name": "action_select_shop", "policy": "policy_3_TEDPolicy", "confidence": 0.9006281495094299}
2020-03-20 03:33:17 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "bot", "timestamp": 1584675197.8804114, "text": "Shop \u0111\u00e3 c\u00f3 t\u00e0i kho\u1ea3n c\u1ee7a GHTK ch\u01b0a \u1ea1?", "data": {"elements": null, "quick_replies": null, "buttons": [{"payload": "khach thuong xuyen", "title": "\u0110\u00e3 c\u00f3 t\u00e0i kho\u1ea3n GHTK"}, {"payload": "khach hang moi", "title": "Ch\u01b0a c\u00f3 t\u00e0i kho\u1ea3n GHTK"}], "attachment": null, "image": null, "custom": null}, "metadata": {}}
2020-03-20 03:33:17 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "slot", "timestamp": 1584675197.8804135, "name": "role", "value": "SHOP"}
2020-03-20 03:33:17 DEBUG    rasa.core.brokers.pika  - Published Pika events to queue 'rasa_production_events' on host '172.16.70.198':
{"sender_id": "test_rasa_x", "event": "action", "timestamp": 1584675197.897225, "name": "action_listen", "policy": "policy_3_TEDPolicy", "confidence": 0.9822789430618286}
2020-03-20 03:33:17 DEBUG    rasa.core.lock_store  - Deleted lock for conversation 'test_rasa_x'.
```
**Rasa X docker-compose.yml summary**:
```yml
...
services:
  rasa-x:
    restart: always
    image: "rasa/rasa-x:${RASA_X_VERSION}"
    ports:
      - "5002:5002"
    volumes:
      - ./models:/app/models
      - ./environments.yml:/app/environments.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./logs:/logs
      - ./auth:/app/auth
    environment:
      <<: *database-credentials
      <<: *rasa-credentials
      SELF_PORT: "5002"
      DB_DATABASE: "${DB_DATABASE:-rasa}"
      RASA_MODEL_DIR: "/app/models"
      PASSWORD_SALT: ${PASSWORD_SALT}
      RABBITMQ_QUEUE: "rasa_production_events"
      RASA_X_USER_ANALYTICS: "0"
      SANIC_RESPONSE_TIMEOUT: "3600"
      DEBUG_MODE: "true"
      # RUN_EVENT_CONSUMER_AS_SEPARATE_SERVICE: "true"
    depends_on:
      - db
  db:
    restart: always
    image: "bitnami/postgresql:11.3.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: "${DB_USER:-admin}"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
      POSTGRESQL_DATABASE: "${DB_DATABASE:-rasa}"
    volumes:
      - ./db:/bitnami/postgresql

  rabbit:
    restart: always
    image: "bitnami/rabbitmq:3.7.17"
    environment:
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
    ports:
      - "5672:5672"
      - "15672:15672"
```

**Rasa X environments.yml**:
```yml
rasa:
    production:
      url: ${RASA_SERVER}:9999
      token: ${RASA_TOKEN}
    worker:
      url: ${RASA_SERVER}:9998
      token: ${RASA_TOKEN}
```
**Rasa opensource docker-compose.yml summary**:
```yml
...
services:
  rasa-production:
    <<: *default-rasa-service
    environment:
      <<: *rasa-credentials
      RASA_ENVIRONMENT: "production"
      DB_DATABASE: "tracker"

  rasa-worker:
    <<: *default-rasa-service
    environment:
      <<: *rasa-credentials
      RASA_ENVIRONMENT: "worker"
      DB_DATABASE: "worker_tracker"

  rasa-action:
    restart: always
    image: "custom_rasa_action"
    expose:
      - "5055"
    depends_on:
      - rasa-production

  redis:
    restart: always
    image: "bitnami/redis:5.0.5"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    expose:
      - "6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rasa-production
      - rasa-worker
      - rasa-action
    ports:
      - "9999:9999"
      - "9998:9998"
```
**Rasa opensource credentials.yml**:
```yml
rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials
rasa:
  url: ${RASA_X_SERVER}/api
```
**Rasa open source endpoints.yml**:
```yml
model:
    url: ${RASA_X_SERVER}/api/projects/default/models/tags/production
    token: lXO5YC20KSQUeqO2BEe+hw==
    wait_time_between_pulls: 10

action_endpoint:
    url: ${ACTION_SERVER}

tracker_store:
    type: redis
    url: ${REDIS_HOST}
    port: ${REDIS_PORT}
    db: ${REDIS_DB}
    password: ${REDIS_PASSWORD}

event_broker:
  type: pika
  url: ${RABBIT_HOST}
  username: ${RABBIT_USER}
  password: ${RABBIT_PASSWORD}
  queue: ${RABBIT_QUEUE}
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
Hey @sinhlt58

Rasa X UI is filtering out conversations between the _active_ user and the bot.
So if you're logged in as `admin` and use `talk to your bot`, the conversation will not be there in the list. 

I hope that helps!

**Comment by sinhlt58** [comment]
Thanks for your response. How can I simulate active users? I chat with the agent using the REST channel with random ids. Does that count as activate users.

When I share the link chat "Share this link with any guest users" the bot get stuck.
![stuck_chat](https://user-images.githubusercontent.com/10632704/77217664-b23e2c80-6b56-11ea-85be-650f9eff4099.png)

But when I check the rasa production log, the conversation still shows up?

![log](https://user-images.githubusercontent.com/10632704/77217714-1103a600-6b57-11ea-96e3-d2497fd180e2.png)

**Comment by sinhlt58** [comment]
My bad guys. I didn't include the endpoints.yml into rasa-x. It works perfectly now. Thanks guys :DDDD
